"""Add minimum depots required to eligibility

Revision ID: 42330befd521
Revises: 5760beb5b967
Create Date: 2026-08-15 16:50:18.596868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = '42330befd521'
down_revision: Union[str, None] = '5760beb5b967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_eligibility', sa.Column('minimum_depots_required', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_eligibility', 'minimum_depots_required')
    # ### end Alembic commands ###
